### ISSUE TITLE
Missing service configs

### ISSUE THREAD

**Issue by ralmn** [docker-client/docker-compose-v3#7]
We are hoping to use your library in a project but need to parse a `configs` inside a `service` inside a`stack` and we realized that the`StackService` doesn't seem to allow it. Would you consider adding it ?
It is described in [the docker documentation](https://docs.docker.com/compose/compose-file/#configs)

```yaml
version: "3.7"

services:
  back:
    image: internal.registry/app-back
    env_file:
      - back.env
    configs:
      - source: shiro
        target: /opt/tomcat/conf/shiro.ini
      - source: catalina
        target: /opt/tomcat/conf/catalina.properties
    deploy: # labels du déploiement
      replicas: 1
configs:
  shiro:
    external: true
    name: app_back_shiro
  catalina:
    external: true
    name: app_catalina_shiro
```
